Repository eslint-community/eslint-plugin-n, pull requests merged in 2024-10, with the labels that each got.

#343 fix(no-missing-import): Resolve tsconfig paths relative to the tsconfig
  lib/util/import-target.js
  tests/fixtures/no-missing/issue-314/module/index.ts
  tests/fixtures/no-missing/issue-314/src/example.ts
  tests/fixtures/no-missing/issue-314/tsconfig.json
  tests/lib/rules/no-missing-import.js
Labels: bug, typescript, rule:update

#350 fix(no-deprecated-api): dedeprecate `process.nextTick`
  lib/rules/no-deprecated-api.js
Labels: bug, rule:update

#358 feat(no-unsupported): Support node 23.0.0 and 22.10.0
  lib/unsupported-features/node-builtins-modules/module.js
  lib/unsupported-features/node-builtins-modules/process.js
  lib/unsupported-features/node-builtins-modules/worker_threads.js
  lib/unsupported-features/node-globals.js
Labels: enhancement, rule:update

#362 fix(no-unsupported): support missing `process.features`
  lib/unsupported-features/node-builtins-modules/process.js
Labels: rule:update

#363 fix(no-unsupported): `getCallSite` is experimental
  lib/unsupported-features/node-builtins-modules/util.js
Labels: rule:update

#365 fix: update dependencies
  .github/release-please/config.json
  .github/release-please/manifest.json
  package.json
Labels: dependencies

#370 feat(no-unsupported): Support node 23.1.0
  lib/unsupported-features/node-builtins-modules/test.js
  lib/unsupported-features/node-builtins-modules/util.js
Labels: rule:update
